### ISSUE TITLE
Feature Request: Allow Toggle to Include config-optional Features

### ISSUE THREAD

**Issue by Padgett** [pacphi/tf4k8s#34]
Optional features should be able to be activated

Example: config-optional/disaster-recovery.yml for backup and restore

**Comment by pacphi** [comment]
This is a pretty simple request to fulfill.  Just need to include the `config-optional` directory, here:  https://github.com/pacphi/tf4k8s/blob/master/modules/tas4k8s/main.tf#L186.

**Comment by pacphi** [comment]
Completed as of 023a8214e164112fe28eabd94709c19a6c9ef2aa.
